"jobs":
  "check":
    "uses": "grafana/loki-release/.github/workflows/check.yml@124c4d996f9625478a79f1884465e29ea082d224"
    "with":
      "build_image": "grafana/loki-build-image:0.33.1"
      "golang_ci_lint_version": "v1.55.1"
      "release_lib_ref": "124c4d996f9625478a79f1884465e29ea082d224"
      "skip_validation": false
      "use_github_app_token": true
"name": "check"
"on":
  "pull_request": {}
  "push":
    "branches":
    - "main"
